steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/highpass-backend:$COMMIT_SHA
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/highpass-backend:$COMMIT_SHA

substitutions:
  _REGION: asia-northeast3
  _REPOSITORY: highpass-artifacts
