spring:
  application:
    name: highpass_backend
  config:
    import: optional:file:env.properties

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/highpassdb
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop   # create / update / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
#            client-secret: ${KAKAO_CLIENT_SECRET}   # 없으면 생략 가능
            authorization-grant-type: authorization_code
            redirect-uri: https://highpass.loca.lt/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
api:
  public-data:
    key: ${PUBLIC_DATA_API_KEY}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}